services:
  kafka:
    image: confluentinc/cp-kafka:7.6.1 # Using a known stable version for testing
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    volumes:
      - ./secrets:/etc/kafka/secrets
    healthcheck:
      test: ["CMD-SHELL", "/usr/bin/kafka-topics.sh --bootstrap-server localhost:9093 --list --command-config /etc/kafka/secrets/client.properties"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s  
    environment:
      CLUSTER_ID: 'MjQ1RDRBRTQtNzYxMy00OD' 
      KAFKA_NODE_ID: 1 
      KAFKA_PROCESS_ROLES: 'broker,controller' 
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093' 
      
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER' 
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092' 
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT' 
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      
      # Topic Settings
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      # mTLS
      KAFKA_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/kafka.server.keystore.jks
      KAFKA_SSL_KEYSTORE_PASSWORD: password
      KAFKA_SSL_KEY_PASSWORD: password
      KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/kafka.server.truststore.jks
      KAFKA_SSL_TRUSTSTORE_PASSWORD: password
      KAFKA_SSL_CLIENT_AUTH: required
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: HTTPS

      KAFKA_LOG_DIRS: /tmp/kafka-logs

      KAFKA_OPTS: "-Djavax.net.debug=ssl"
      KAFKA_HEAP_OPTS: "-Xms256m -Xmx1g"
    
  kong:
    image: 'kong/kong-gateway:3.10.0.5'
    container_name: kong
    depends_on:
      - kafka
    network_mode: host
    volumes:
      - ./kong:/kong
      - ./secrets:/etc/secrets
    environment:
      KONG_DATABASE: off
      KONG_DECLARATIVE_CONFIG: /kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_URL: http://localhost:8002
      KONG_LICENSE_DATA: ${KONG_LICENSE_DATA}
      KONG_CLIENT_SSL_CERT: /etc/secrets/kafka.client.crt
      KONG_CLIENT_SSL_CERT_KEY: /etc/secrets/kafka.client.key
      KONG_NGINX_PROXY_PROXY_SSL_TRUSTED_CERTIFICATE: /etc/secrets/ca.crt
      KONG_LUA_SSL_TRUSTED_CERTIFICATE: /etc/secrets/ca.crt
